/*{
	"DESCRIPTION": "Emissary Loom Expanded — Murmuration, iterated. The second field test of the LOOM-TASTE loop (2026-07-12): the operator took the Brave AI follow-up suggestions as a USER would ('animate the predator', 'add wind turbulence', 'make flock colors dynamic over time') and the seat implemented them app-side — the AIGENT extend-an-existing-shader product flow, rehearsed. New: the predator HUNTS (autonomous flight blended with the held position), the wind GUSTS (time-varying strength + direction wobble), the flock is IRIDESCENT (two-swatch shimmer coupled to density). T2 lessons applied in the same pass: predator position is ONE point2D (was x/y float pair), exact attribution kept.",
	"CREDIT": "Base: Generated by Brave AI on 2026-07-12 (midday CEST). Expansion: Loom (Fable 5, Kintsugi seat) implementing the Brave AI follow-up suggestions, same day — per portrait-lineage rules in specs/loom-identity.md 5.1 territory + LOOM-TASTE T3.",
	"ISFVSN": "2",
	"CATEGORIES": [ "GENERATOR" ],
	"INPUTS": [
		{ "NAME": "flockSpeed", "TYPE": "float", "LABEL": "flock speed", "DEFAULT": 0.15, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "windDir", "TYPE": "point2D", "LABEL": "wind direction", "DEFAULT": [ 0.5, 0.5 ], "MIN": [ 0.0, 0.0 ], "MAX": [ 1.0, 1.0 ], "_groupId": "motion" },
		{ "NAME": "turbulence", "TYPE": "float", "LABEL": "air turbulence", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "curlStrength", "TYPE": "float", "LABEL": "curl force", "DEFAULT": 0.6, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "drift", "TYPE": "float", "LABEL": "base drift", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 2.0, "_groupId": "motion" },
		{ "NAME": "gustStrength", "TYPE": "float", "LABEL": "gust strength", "DEFAULT": 0.35, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "gustRate", "TYPE": "float", "LABEL": "gust rate", "DEFAULT": 0.3, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },

		{ "NAME": "densityBase", "TYPE": "float", "LABEL": "base density", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "gatherTightness", "TYPE": "float", "LABEL": "gather tightness", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "flockScale", "TYPE": "float", "LABEL": "flock scale", "DEFAULT": 1.2, "MIN": 0.1, "MAX": 3.0, "_groupId": "shape" },
		{ "NAME": "memberSize", "TYPE": "float", "LABEL": "bird size", "DEFAULT": 0.45, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "attenuation", "TYPE": "float", "LABEL": "bird softness", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "flockRot", "TYPE": "float", "LABEL": "flock rotation", "DEFAULT": 0.0, "MIN": -180.0, "MAX": 180.0, "_groupId": "shape" },
		{ "NAME": "predatorPos", "TYPE": "point2D", "LABEL": "predator position", "DEFAULT": [ 0.5, 0.5 ], "MIN": [ 0.0, 0.0 ], "MAX": [ 1.0, 1.0 ], "_groupId": "predator" },
		{ "NAME": "predatorForce", "TYPE": "float", "LABEL": "predator force", "DEFAULT": 0.8, "MIN": 0.0, "MAX": 1.5, "_groupId": "predator" },
		{ "NAME": "predatorHunt", "TYPE": "float", "LABEL": "predator hunt", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "predator" },
		{ "NAME": "huntSpeed", "TYPE": "float", "LABEL": "hunt speed", "DEFAULT": 0.25, "MIN": 0.0, "MAX": 1.0, "_groupId": "predator" },

		{ "NAME": "colorFlock", "TYPE": "color", "LABEL": "flock body", "DEFAULT": [ 0.05, 0.05, 0.08, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorSheen", "TYPE": "color", "LABEL": "flock sheen", "DEFAULT": [ 0.18, 0.12, 0.28, 1.0 ], "_groupId": "color" },
		{ "NAME": "shimmerRate", "TYPE": "float", "LABEL": "shimmer rate", "DEFAULT": 0.3, "MIN": 0.0, "MAX": 1.0, "_groupId": "color" },
		{ "NAME": "colorSkyTop", "TYPE": "color", "LABEL": "sky top", "DEFAULT": [ 0.1, 0.05, 0.2, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorSkyBot", "TYPE": "color", "LABEL": "sky bottom", "DEFAULT": [ 0.6, 0.3, 0.1, 1.0 ], "_groupId": "color" }
	]
}*/

// Emissary Expanded — the iteration test. Base flock by Brave AI; the three
// follow-up features implemented by the seat: hunting predator (Lissajous
// flight blended with the held position — the position control becomes the
// CENTER of its territory as hunt rises), gusting wind (fbm-driven strength
// swell + direction wobble), iridescent flock (two-swatch shimmer coupled to
// density — dense knots flash sheen the way real starling backs catch dusk).
// T2 lessons applied: predator = ONE point2D; labels lowercase; loops
// fixed-bound (canon: pipeline.md GL Context Rules).

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    float a = hash(i);
    float b = hash(i + vec2(1.0, 0.0));
    float c = hash(i + vec2(0.0, 1.0));
    float d = hash(i + vec2(1.0, 1.0));
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

float fbm(vec2 p, int octaves, float lacunarity, float gain) {
    float value = 0.0;
    float amplitude = 0.5;
    float frequency = 1.0;
    for (int i = 0; i < 5; i++) {      // fixed bound
        if (i >= octaves) break;       // runtime break
        value += amplitude * noise(p * frequency);
        frequency *= lacunarity;
        amplitude *= gain;
    }
    return value;
}

vec2 curlNoise(vec2 p, float strength) {
    float e = 0.01;
    float n1 = noise(p);
    float n2 = noise(p + vec2(e, 0.0));
    float n3 = noise(p + vec2(0.0, e));
    float dx = (n2 - n1) / e;
    float dy = (n3 - n1) / e;
    return vec2(-dy, dx) * strength;
}

void main() {
    float aspect = RENDERSIZE.x / RENDERSIZE.y;
    vec2 uv = gl_FragCoord.xy / RENDERSIZE.xy;
    uv.x *= aspect;

    float t = TIME * flockSpeed;
    // T7 "declare the obvious" (LOOM-TASTE): whole-flock orientation + base
    // drift alive at defaults — the piece must MOVE untouched.
    vec2 rc = vec2(0.5 * aspect, 0.5);
    float ra = radians(flockRot);
    float rcs = cos(ra); float rsn = sin(ra);
    vec2 ruv = uv - rc;  /* uv is already aspect-scaled in this file */
    ruv = vec2(ruv.x * rcs - ruv.y * rsn, ruv.x * rsn + ruv.y * rcs) + rc;
    vec2 driftVec = vec2(TIME * drift * 0.045, TIME * drift * 0.018);


    // ---- FEATURE 2: gusting wind — strength swells and direction wobbles ----
    float gustT = TIME * (0.1 + gustRate * 0.8);
    float gust = 1.0 + gustStrength * 2.0 * (fbm(vec2(gustT, 3.7), 3, 2.0, 0.5) - 0.5);
    float wobble = gustStrength * 0.8 * (noise(vec2(gustT * 0.7, 9.1)) - 0.5);
    vec2 windBase = (windDir - 0.5) * 2.0;
    // rotate the wind vector by the wobble angle
    float cw = cos(wobble);
    float sw = sin(wobble);
    vec2 wind = vec2(windBase.x * cw - windBase.y * sw,
                     windBase.x * sw + windBase.y * cw) * gust;

    vec2 flowPos = ruv * flockScale + driftVec;
    float n1 = fbm(flowPos + vec2(t * 0.1, 0.0), 4, 2.0, 0.5);
    float n2 = fbm(flowPos * 1.5 - vec2(0.0, t * 0.05), 3, 2.0, 0.6);
    vec2 curl = curlNoise(flowPos * 2.0 + t * 0.2, curlStrength);
    vec2 flow = vec2(n1, n2) * turbulence + curl + wind * 0.3;

    float density = 0.0;
    for (int i = 0; i < 4; i++) {      // fixed bound
        vec2 layerPos = ruv + driftVec + flow * (0.1 + float(i) * 0.05);
        float layerNoise = fbm(layerPos * (2.0 + float(i)), 3, 2.0, 0.5);
        density += layerNoise * (1.0 - float(i) * 0.2);
    }
    density = density / 2.5;
    density = pow(density, gatherTightness * 0.5 + 0.5);
    density = clamp(density * densityBase * 2.0, 0.0, 1.0);
    // T7: the MEMBERS — individual birds as high-frequency grain riding the
    // density mass; bird size = grain scale, bird softness = attenuation.
    float mFreq = mix(220.0, 40.0, memberSize);
    float mGrain = noise(ruv * mFreq + flow * 8.0 + driftVec * mFreq * 0.2 + vec2(t * 3.0, t * 2.0));
    float mSharp = mix(3.5, 0.7, attenuation);
    float members = pow(clamp(mGrain, 0.0, 1.0), mSharp);
    density *= mix(0.75, 1.35, members);


    // ---- FEATURE 1: the hunting predator — Lissajous flight around the held
    // position; predatorHunt blends held (0) -> full autonomous roam (1) ----
    float ht = TIME * (0.05 + huntSpeed * 0.6);
    vec2 flight = vec2(sin(ht * 1.0) * 0.5 + sin(ht * 2.7) * 0.18,
                       cos(ht * 1.3) * 0.4 + cos(ht * 3.1) * 0.15);
    vec2 predBase = vec2(predatorPos.x * aspect, predatorPos.y);
    vec2 predNow = predBase + flight * predatorHunt * 0.35 * vec2(aspect, 1.0);
    float distToPredator = distance(uv, predNow);
    float predatorInfluence = exp(-distToPredator * 3.0 * predatorForce);
    density *= (1.0 - predatorInfluence * 0.9);

    float edgeFade = smoothstep(0.0, 0.1, density) * smoothstep(1.0, 0.8, density);
    density *= edgeFade;

    vec3 skyColor = mix(colorSkyBot.rgb, colorSkyTop.rgb, uv.y);

    // ---- FEATURE 3: iridescent flock — two-swatch shimmer coupled to density,
    // so the dense knots flash sheen the way starling backs catch the dusk ----
    float shimmer = 0.5 + 0.5 * sin(TIME * shimmerRate * 3.0 + density * 6.0 + uv.x * 2.0);
    vec3 flockColor = mix(colorFlock.rgb, colorSheen.rgb, shimmer * density);
    float depthShade = 1.0 - density * 0.7;
    flockColor *= depthShade;

    vec3 finalColor = mix(skyColor, flockColor, density * colorFlock.a);
    gl_FragColor = vec4(finalColor, 1.0);
}
