/*{
	"DESCRIPTION": "Murmuration: A living mass of starlings sculpted by layered noise fields, curling and densifying over a dusk sky, pushed by a single predator pressure. Emissary Brave Expanded — the generating agent's own interpretation of the three expansion features. Landed 2026-07-12 with TWO repairs: local shadowing of the predatorPos uniform renamed (GLSL ES scoping risk) + predator family regrouped to its own accordion per LOOM-TASTE T4 (the prompt predated the rule). Comparative audit vs the seat's twin interpretation: LOOM-TASTE T5.",
	"CREDIT": "Base + expansion generated by Brave AI on 2026-07-12 12:16 UTC. Base originally generated by Brave AI on 2026-07-12. Repairs + landing: Loom (Fable 5, Kintsugi seat).",
	"ISFVSN": "2.0",
	"CATEGORIES": [ "GENERATOR" ],
	"INPUTS": [
		{ "NAME": "flockSpeed", "TYPE": "float", "LABEL": "flock speed", "DEFAULT": 0.15, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "windDir", "TYPE": "point2D", "LABEL": "wind direction", "DEFAULT": [ 0.5, 0.5 ], "MIN": [ 0.0, 0.0 ], "MAX": [ 1.0, 1.0 ], "_groupId": "motion" },
		{ "NAME": "turbulence", "TYPE": "float", "LABEL": "air turbulence", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "curlStrength", "TYPE": "float", "LABEL": "curl force", "DEFAULT": 0.6, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "drift", "TYPE": "float", "LABEL": "base drift", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 2.0, "_groupId": "motion" },
		{ "NAME": "gustStrength", "TYPE": "float", "LABEL": "gust strength", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "gustSpeed", "TYPE": "float", "LABEL": "gust speed", "DEFAULT": 0.3, "MIN": 0.0, "MAX": 2.0, "_groupId": "motion" },

		{ "NAME": "densityBase", "TYPE": "float", "LABEL": "base density", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "gatherTightness", "TYPE": "float", "LABEL": "gather tightness", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "flockScale", "TYPE": "float", "LABEL": "flock scale", "DEFAULT": 1.2, "MIN": 0.1, "MAX": 3.0, "_groupId": "shape" },
		{ "NAME": "memberSize", "TYPE": "float", "LABEL": "bird size", "DEFAULT": 0.45, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "attenuation", "TYPE": "float", "LABEL": "bird softness", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "flockRot", "TYPE": "float", "LABEL": "flock rotation", "DEFAULT": 0.0, "MIN": -180.0, "MAX": 180.0, "_groupId": "shape" },

		{ "NAME": "predatorPos", "TYPE": "point2D", "LABEL": "predator anchor", "DEFAULT": [ 0.5, 0.5 ], "MIN": [ 0.0, 0.0 ], "MAX": [ 1.0, 1.0 ], "_groupId": "predator" },
		{ "NAME": "predatorForce", "TYPE": "float", "LABEL": "predator force", "DEFAULT": 0.8, "MIN": 0.0, "MAX": 1.5, "_groupId": "predator" },
		{ "NAME": "predatorAuto", "TYPE": "float", "LABEL": "predator autonomy", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "predator" },
		{ "NAME": "predatorOrbitSpeed", "TYPE": "float", "LABEL": "predator orbit speed", "DEFAULT": 0.2, "MIN": 0.0, "MAX": 1.0, "_groupId": "predator" },
		{ "NAME": "predatorOrbitRadius", "TYPE": "float", "LABEL": "predator orbit radius", "DEFAULT": 0.25, "MIN": 0.0, "MAX": 0.5, "_groupId": "predator" },

		{ "NAME": "colorFlock", "TYPE": "color", "LABEL": "flock body color", "DEFAULT": [ 0.05, 0.05, 0.08, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorFlockShimmer", "TYPE": "color", "LABEL": "flock shimmer color", "DEFAULT": [ 0.3, 0.25, 0.4, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorSkyTop", "TYPE": "color", "LABEL": "sky top color", "DEFAULT": [ 0.1, 0.05, 0.2, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorSkyBot", "TYPE": "color", "LABEL": "sky bottom color", "DEFAULT": [ 0.6, 0.3, 0.1, 1.0 ], "_groupId": "color" },
		{ "NAME": "shimmerIntensity", "TYPE": "float", "LABEL": "shimmer intensity", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "color" }
	]
}*/

// Noise functions
float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    float a = hash(i);
    float b = hash(i + vec2(1.0, 0.0));
    float c = hash(i + vec2(0.0, 1.0));
    float d = hash(i + vec2(1.0, 1.0));
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

float fbm(vec2 p, int octaves, float lacunarity, float gain) {
    float value = 0.0;
    float amplitude = 0.5;
    float frequency = 1.0;
    for (int i = 0; i < 5; i++) {
        if (i >= octaves) break;
        value += amplitude * noise(p * frequency);
        frequency *= lacunarity;
        amplitude *= gain;
    }
    return value;
}

// Curl noise approximation
vec2 curlNoise(vec2 p, float strength) {
    float e = 0.01;
    float n1 = noise(p);
    float n2 = noise(p + vec2(e, 0.0));
    float n3 = noise(p + vec2(0.0, e));
    float dx = (n2 - n1) / e;
    float dy = (n3 - n1) / e;
    return vec2(-dy, dx) * strength;
}

void main() {
    // Aspect correct coordinates
    vec2 uv = gl_FragCoord.xy / RENDERSIZE.xy;
    float aspect = RENDERSIZE.x / RENDERSIZE.y;
    vec2 uvAspect = vec2(uv.x * aspect, uv.y);

    // Time-based movement
    float t = TIME * flockSpeed;
    // T7 "declare the obvious" (LOOM-TASTE): whole-flock orientation + base
    // drift alive at defaults — the piece must MOVE untouched.
    vec2 rc = vec2(0.5 * aspect, 0.5);
    float ra = radians(flockRot);
    float rcs = cos(ra); float rsn = sin(ra);
    vec2 ruv = uvAspect - rc;
    ruv = vec2(ruv.x * rcs - ruv.y * rsn, ruv.x * rsn + ruv.y * rcs) + rc;
    vec2 driftVec = vec2(TIME * drift * 0.045, TIME * drift * 0.018);


    // Wind turbulence - organic gusting
    float gustTime = TIME * (0.5 + gustSpeed * 1.5);
    float gustX = sin(gustTime) * cos(gustTime * 0.7) * gustStrength;
    float gustY = cos(gustTime * 0.9) * sin(gustTime * 0.4) * gustStrength;
    vec2 windBase = (windDir - 0.5) * 2.0;
    vec2 wind = windBase + vec2(gustX, gustY);

    // Base flow field with multiple octaves
    vec2 flowPos = ruv * flockScale + driftVec;
    float n1 = fbm(flowPos + vec2(t * 0.1, 0.0), 4, 2.0, 0.5);
    float n2 = fbm(flowPos * 1.5 - vec2(0.0, t * 0.05), 3, 2.0, 0.6);

    // Curl noise for organic movement
    vec2 curl = curlNoise(flowPos * 2.0 + t * 0.2, curlStrength);

    // Combine flows
    vec2 flow = vec2(n1, n2) * turbulence + curl + wind * 0.3;

    // Density field calculation
    float density = 0.0;
    vec2 samplePos = uv;

    // Layered density bands
    for (int i = 0; i < 4; i++) {
        float layerTime = t * (1.0 + float(i) * 0.2);
        vec2 layerPos = ruv + driftVec + flow * (0.1 + float(i) * 0.05);
        float layerNoise = fbm(layerPos * (2.0 + float(i)), 3, 2.0, 0.5);
        density += layerNoise * (1.0 - float(i) * 0.2);
    }

    density = density / 2.5;
    density = pow(density, gatherTightness * 0.5 + 0.5);
    density = clamp(density * densityBase * 2.0, 0.0, 1.0);
    // T7: the MEMBERS — individual birds as high-frequency grain riding the
    // density mass; bird size = grain scale, bird softness = attenuation.
    float mFreq = mix(220.0, 40.0, memberSize);
    float mGrain = noise(ruv * mFreq + flow * 8.0 + driftVec * mFreq * 0.2 + vec2(t * 3.0, t * 2.0));
    float mSharp = mix(3.5, 0.7, attenuation);
    float members = pow(clamp(mGrain, 0.0, 1.0), mSharp);
    density *= mix(0.75, 1.35, members);


    // Animated predator position
    // EMISSARY REPAIR: the original declared `vec2 predatorPos = mix(predatorPos, ...)`
    // — a local shadowing the predatorPos UNIFORM (illegal/fragile in GLSL ES).
    // Renamed the local; math verbatim.
    float orbitTime = TIME * (0.5 + predatorOrbitSpeed * 2.0);
    vec2 orbitOffset = vec2(
        cos(orbitTime) * predatorOrbitRadius,
        sin(orbitTime * 0.7) * predatorOrbitRadius
    );
    vec2 predNow = mix(predatorPos, predatorPos + orbitOffset, predatorAuto);

    // Predator influence - creates a hole in the flock
    vec2 predatorPosAspect = vec2(predNow.x * aspect, predNow.y);
    float distToPredator = distance(uvAspect, predatorPosAspect);
    float predatorInfluence = exp(-distToPredator * 3.0 * predatorForce);
    density *= (1.0 - predatorInfluence * 0.9);

    // Create wispy edges
    float edgeFade = smoothstep(0.0, 0.1, density) * smoothstep(1.0, 0.8, density);
    density *= edgeFade;

    // Sky gradient background
    vec3 skyColor = mix(colorSkyBot.rgb, colorSkyTop.rgb, uv.y);

    // Dynamic flock color with shimmer
    float shimmerTime = TIME * 0.3;
    float shimmerNoise = fbm(uv * 3.0 + vec2(shimmerTime, shimmerTime * 0.5), 3, 2.0, 0.5);
    float shimmerFactor = shimmerNoise * shimmerIntensity;
    vec3 flockBaseColor = mix(colorFlock.rgb, colorFlockShimmer.rgb, shimmerFactor);

    // Depth variation
    float depthShade = 1.0 - density * 0.7;
    vec3 flockColor = flockBaseColor * depthShade;

    // Final composite
    vec3 finalColor = mix(skyColor, flockColor, density * colorFlock.a);

    gl_FragColor = vec4(finalColor, 1.0);
}
