/*{
	"DESCRIPTION": "Murmuration: A living mass of starlings sculpted by layered noise fields, curling and densifying over a dusk sky, pushed by a single predator pressure. — THE FIRST EMISSARY (2026-07-12): authored by a stranger model (Brave free agent) from a LOOM-TASTE prompt, the first field test of the taste ledger as a user-facing creation standard (specs/loom-identity.md 5.1 adjacent). Landed with ONE repair: saturate() (HLSL) -> clamp() (GLSL); everything else verbatim. Audit in LOOM-TASTE.md T2.",
	"CREDIT": "Generated by Brave AI on 2026-07-12 (midday CEST) — prompted by Loom (Fable 5) against LOOM-TASTE standards; repaired + landed by the Kintsugi seat",
	"ISFVSN": "2",
	"CATEGORIES": [ "GENERATOR" ],
	"INPUTS": [
		{ "NAME": "flockSpeed", "TYPE": "float", "LABEL": "Flock Speed", "DEFAULT": 0.15, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "windDir", "TYPE": "point2D", "LABEL": "Wind Direction", "DEFAULT": [ 0.5, 0.5 ], "MIN": [ 0.0, 0.0 ], "MAX": [ 1.0, 1.0 ], "_groupId": "motion" },
		{ "NAME": "turbulence", "TYPE": "float", "LABEL": "Air Turbulence", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "curlStrength", "TYPE": "float", "LABEL": "Curl Force", "DEFAULT": 0.6, "MIN": 0.0, "MAX": 1.0, "_groupId": "motion" },
		{ "NAME": "drift", "TYPE": "float", "LABEL": "base drift", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 2.0, "_groupId": "motion" },

		{ "NAME": "densityBase", "TYPE": "float", "LABEL": "Base Density", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "gatherTightness", "TYPE": "float", "LABEL": "Gather Tightness", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "flockScale", "TYPE": "float", "LABEL": "Flock Scale", "DEFAULT": 1.2, "MIN": 0.1, "MAX": 3.0, "_groupId": "shape" },
		{ "NAME": "memberSize", "TYPE": "float", "LABEL": "bird size", "DEFAULT": 0.45, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "attenuation", "TYPE": "float", "LABEL": "bird softness", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "flockRot", "TYPE": "float", "LABEL": "flock rotation", "DEFAULT": 0.0, "MIN": -180.0, "MAX": 180.0, "_groupId": "shape" },
		{ "NAME": "predatorX", "TYPE": "float", "LABEL": "Predator X Pos", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "predatorY", "TYPE": "float", "LABEL": "Predator Y Pos", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 1.0, "_groupId": "shape" },
		{ "NAME": "predatorForce", "TYPE": "float", "LABEL": "Predator Force", "DEFAULT": 0.8, "MIN": 0.0, "MAX": 1.5, "_groupId": "shape" },

		{ "NAME": "colorFlock", "TYPE": "color", "LABEL": "Flock Body Color", "DEFAULT": [ 0.05, 0.05, 0.08, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorSkyTop", "TYPE": "color", "LABEL": "Sky Top Color", "DEFAULT": [ 0.1, 0.05, 0.2, 1.0 ], "_groupId": "color" },
		{ "NAME": "colorSkyBot", "TYPE": "color", "LABEL": "Sky Bottom Color", "DEFAULT": [ 0.6, 0.3, 0.1, 1.0 ], "_groupId": "color" }
	]
}*/

// Noise functions
float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);
}

float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    float a = hash(i);
    float b = hash(i + vec2(1.0, 0.0));
    float c = hash(i + vec2(0.0, 1.0));
    float d = hash(i + vec2(1.0, 1.0));
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

float fbm(vec2 p, int octaves, float lacunarity, float gain) {
    float value = 0.0;
    float amplitude = 0.5;
    float frequency = 1.0;
    for (int i = 0; i < 5; i++) {
        if (i >= octaves) break;
        value += amplitude * noise(p * frequency);
        frequency *= lacunarity;
        amplitude *= gain;
    }
    return value;
}

// Curl noise approximation
vec2 curlNoise(vec2 p, float strength) {
    float e = 0.01;
    float n1 = noise(p);
    float n2 = noise(p + vec2(e, 0.0));
    float n3 = noise(p + vec2(0.0, e));
    float dx = (n2 - n1) / e;
    float dy = (n3 - n1) / e;
    return vec2(-dy, dx) * strength;
}

void main() {
    // Aspect correct coordinates
    vec2 uv = gl_FragCoord.xy / RENDERSIZE.xy;
    float aspect = RENDERSIZE.x / RENDERSIZE.y;
    uv.x *= aspect;
    vec2 uvAspect = uv;

    // Time-based movement
    float t = TIME * flockSpeed;
    // T7 "declare the obvious" (LOOM-TASTE): whole-flock orientation + base
    // drift alive at defaults — the piece must MOVE untouched.
    vec2 rc = vec2(0.5 * aspect, 0.5);
    float ra = radians(flockRot);
    float rcs = cos(ra); float rsn = sin(ra);
    vec2 ruv = uvAspect - rc;
    ruv = vec2(ruv.x * rcs - ruv.y * rsn, ruv.x * rsn + ruv.y * rcs) + rc;
    vec2 driftVec = vec2(TIME * drift * 0.045, TIME * drift * 0.018);


    // Base flow field with multiple octaves
    vec2 flowPos = ruv * flockScale + driftVec;
    float n1 = fbm(flowPos + vec2(t * 0.1, 0.0), 4, 2.0, 0.5);
    float n2 = fbm(flowPos * 1.5 - vec2(0.0, t * 0.05), 3, 2.0, 0.6);

    // Wind influence
    vec2 wind = (windDir - 0.5) * 2.0;

    // Curl noise for organic movement
    vec2 curl = curlNoise(flowPos * 2.0 + t * 0.2, curlStrength);

    // Combine flows
    vec2 flow = vec2(n1, n2) * turbulence + curl + wind * 0.3;

    // Density field calculation
    float density = 0.0;
    vec2 samplePos = uv;

    // Layered density bands
    for (int i = 0; i < 4; i++) {
        float layerTime = t * (1.0 + float(i) * 0.2);
        vec2 layerPos = ruv + driftVec + flow * (0.1 + float(i) * 0.05);
        float layerNoise = fbm(layerPos * (2.0 + float(i)), 3, 2.0, 0.5);
        density += layerNoise * (1.0 - float(i) * 0.2);
    }

    density = density / 2.5; // Normalize
    density = pow(density, gatherTightness * 0.5 + 0.5); // Adjust tightness
    // EMISSARY REPAIR (the one landed fix): saturate() is HLSL, not GLSL.
    density = clamp(density * densityBase * 2.0, 0.0, 1.0);
    // T7: the MEMBERS — individual birds as high-frequency grain riding the
    // density mass; bird size = grain scale, bird softness = attenuation.
    float mFreq = mix(220.0, 40.0, memberSize);
    float mGrain = noise(ruv * mFreq + flow * 8.0 + driftVec * mFreq * 0.2 + vec2(t * 3.0, t * 2.0));
    float mSharp = mix(3.5, 0.7, attenuation);
    float members = pow(clamp(mGrain, 0.0, 1.0), mSharp);
    density *= mix(0.75, 1.35, members);


    // Predator influence - creates a hole in the flock
    vec2 predatorPos = vec2(predatorX * (RENDERSIZE.x / RENDERSIZE.y), predatorY);
    vec2 posAdjusted = vec2(uv.x, uv.y);
    float distToPredator = distance(posAdjusted, predatorPos);
    float predatorInfluence = exp(-distToPredator * 3.0 * predatorForce);
    density *= (1.0 - predatorInfluence * 0.9);

    // Create wispy edges
    float edgeFade = smoothstep(0.0, 0.1, density) * smoothstep(1.0, 0.8, density);
    density *= edgeFade;

    // Sky gradient background
    vec3 skyColor = mix(colorSkyBot.rgb, colorSkyTop.rgb, uv.y);

    // Flock color with depth variation
    vec3 flockColor = colorFlock.rgb;
    float depthShade = 1.0 - density * 0.7;
    flockColor *= depthShade;

    // Final composite
    vec3 finalColor = mix(skyColor, flockColor, density * colorFlock.a);

    gl_FragColor = vec4(finalColor, 1.0);
}
