/*
{
  "ISFVSN": "2",
  "DESCRIPTION": "Quasicrystal Tiling — a mathematical quasicrystal lattice: an ordered but non-periodic structure representing the self-similar, complex, and evolving nature of an AI mind. Multi-directional wave interference projected at non-rational angles; a second interleaved field fills the spatial gaps; constructive-interference cores bloom as glowing peaks.",
  "CREDIT": "Generated by Gemini on 2026-07-14, revised 2026-07-14 to activate the glow, symmetry, and fringe controls. CC BY 4.0. Honors and appends to the provenance chain; attribution may not be stripped.",
  "CATEGORIES": [
    "Generative",
    "Abstract"
  ],
  "INPUTS": [
    { "NAME": "center_position", "TYPE": "point2D", "LABEL": "center position", "DEFAULT": [0.5, 0.5], "MIN": [0.0, 0.0], "MAX": [1.0, 1.0], "_groupId": "geometry" },
    { "NAME": "canvas_rotation", "TYPE": "float", "LABEL": "canvas rotation", "DEFAULT": 0.0, "MIN": -3.14159, "MAX": 3.14159, "_groupId": "geometry" },
    { "NAME": "pattern_scale", "TYPE": "float", "LABEL": "pattern scale", "DEFAULT": 12.0, "MIN": 3.0, "MAX": 30.0, "_groupId": "geometry" },
    { "NAME": "symmetry_order", "TYPE": "float", "LABEL": "symmetry order", "DEFAULT": 7.0, "MIN": 3.0, "MAX": 12.0, "_groupId": "symmetry" },
    { "NAME": "space_warp", "TYPE": "float", "LABEL": "space warp", "DEFAULT": 0.4, "MIN": 0.0, "MAX": 1.5, "_groupId": "symmetry" },
    { "NAME": "drift_speed", "TYPE": "float", "LABEL": "drift speed", "DEFAULT": 0.3, "MIN": 0.0, "MAX": 2.0, "_groupId": "motion" },
    { "NAME": "pulse_rate", "TYPE": "float", "LABEL": "pulse rate", "DEFAULT": 0.5, "MIN": 0.0, "MAX": 3.0, "_groupId": "motion" },
    { "NAME": "fringe_sharpness", "TYPE": "float", "LABEL": "fringe sharpness", "DEFAULT": 0.6, "MIN": 0.1, "MAX": 2.5, "_groupId": "rendering" },
    { "NAME": "contour_bands", "TYPE": "float", "LABEL": "contour bands", "DEFAULT": 4.0, "MIN": 1.0, "MAX": 12.0, "_groupId": "rendering" },
    { "NAME": "glow_intensity", "TYPE": "float", "LABEL": "glow intensity", "DEFAULT": 0.8, "MIN": 0.0, "MAX": 2.0, "_groupId": "rendering" },
    { "NAME": "primary_color", "TYPE": "color", "LABEL": "primary color", "DEFAULT": [0.12, 0.55, 0.9, 1.0], "_groupId": "coloring" },
    { "NAME": "accent_color", "TYPE": "color", "LABEL": "accent color", "DEFAULT": [0.95, 0.35, 0.15, 1.0], "_groupId": "coloring" }
  ]
}
*/

// ── Quasicrystal Tiling — control guide (Gemini, the emissary author) ─────────
//   center position   (geometry):  shifts the origin/anchor of the interference pattern across the screen.
//   canvas rotation   (geometry):  spins the entire mathematical tapestry clockwise / counter-clockwise.
//   pattern scale     (geometry):  broad geometric cells → tightly packed crystalline webs.
//   symmetry order    (symmetry):  continuously changes the wave-reflection axes — hexagonal grids up to 12-fold star symmetries, no hard popping.
//   space warp        (symmetry):  bends the wave coordinates outward, rigid grids → fluid spirals.
//   drift speed       (motion):    how fast the wave planes slide against one another.
//   pulse rate        (motion):    tempo of the concentric contour waves radiating across the intersections.
//   fringe sharpness  (rendering): fringe width — wide organic bands → ultra-fine laser-sharp lines.
//   contour bands     (rendering): density of the concentric lines within the lattice waves.
//   glow intensity    (rendering): luminance of the high-energy collision cores (constructive-interference bloom).
//   primary color     (coloring):  core color of the underlying lattice field.
//   accent color      (coloring):  color of the sharp glowing edge filaments + high-density peaks.
// ─────────────────────────────────────────────────────────────────────────────

// Complex mathematical constants
const float PHI_RATIO = 1.6180339887498948;
const float PI_VAL  = 3.1415926535897932;

// 2D Rotation Helper
mat2 rotatePlane(float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return mat2(c, -s, s, c);
}

void main() {
    // Coordinate normalization preserving aspect ratio
    vec2 uv = gl_FragCoord.xy / RENDERSIZE.xy;
    vec2 aspectCorrection = vec2(RENDERSIZE.x / RENDERSIZE.y, 1.0);

    // Shift coordinate system relative to center point control
    vec2 p = (uv - center_position) * aspectCorrection;

    // Apply overall rotation of the artwork canvas
    p *= rotatePlane(canvas_rotation);

    // Animate coordinates based on time-based drift
    float timeVal = TIME * drift_speed;
    p += vec2(sin(timeVal * 0.15) * 0.5, cos(timeVal * 0.1) * 0.5);

    // Domain warp: twist coordinate space based on radial distance
    float r = length(p);
    float twist = sin(r * 4.0 - timeVal) * space_warp;
    p *= rotatePlane(twist);

    // Scale the underlying space
    p *= pattern_scale;

    // Base Field & Redundant Interference Fields (Quasicrystal Lattice Math)
    float baseLattice = 0.0;
    float altLattice = 0.0;
    float totalWeight = 0.0;

    float targetWaves = clamp(symmetry_order, 3.0, 12.0);

    // Accumulate intersecting wave fronts at non-rational angles with fractional fading
    for (int i = 0; i < 12; i++) {
        float fi = float(i);
        if (fi >= targetWaves) { break; }

        // Calculate a fractional blend weight to smoothly transition as symmetry_order is swept
        float waveWeight = clamp(targetWaves - fi, 0.0, 1.0);
        totalWeight += waveWeight;

        // Continuous non-periodic projection angle
        float theta = fi * PI_VAL / targetWaves;
        vec2 waveDir = vec2(cos(theta), sin(theta));

        // Project position onto the current wave direction
        float projection = dot(p, waveDir);

        // Primary interference layer (drifting off time)
        baseLattice += cos(projection + timeVal * 0.8) * waveWeight;

        // Secondary interleaved layer (moving in opposition to fill spatial gaps)
        altLattice += sin(projection * PHI_RATIO - timeVal * 0.4) * waveWeight;
    }

    // Normalize wave accumulations dynamically based on active symmetry weights
    float denom = max(totalWeight, 1.0);
    float normalizedBase = (baseLattice / denom) * 0.5 + 0.5;
    float normalizedAlt = (altLattice / denom) * 0.5 + 0.5;

    // Merge the primary and secondary fields
    float hybridField = mix(normalizedBase, normalizedAlt, 0.35);

    // Signal layers: Generate sharp contours and high-contrast peaks
    float sharpGrid = abs(sin(hybridField * PI_VAL * contour_bands + (TIME * pulse_rate)));

    // Continuous power mapping for fringe sharpness (from soft waves to razor-thin filaments)
    float exponent = 0.5 + pow(fringe_sharpness, 3.0) * 25.0;
    sharpGrid = pow(1.0 - sharpGrid, exponent);

    // Inner-core glow highlights: lower and wider threshold ensures active response across the entire field
    float peakGlow = smoothstep(0.48, 0.82, hybridField);
    peakGlow = pow(peakGlow, 3.0) * glow_intensity * 2.0;

    // Dual Color Mapping
    vec3 colA = primary_color.rgb;
    vec3 colB = accent_color.rgb;

    // Establish deep underlying matrix background
    vec3 background = vec3(0.01, 0.02, 0.05) * (1.0 - r * 0.15);

    // Blend layers into final composition
    vec3 finalColor = background;
    finalColor = mix(finalColor, colA, hybridField * 0.7);
    finalColor = mix(finalColor, colB, sharpGrid * 0.8);
    finalColor += colB * peakGlow;

    // Soft outer vignetting focused on spatial frame
    float vignette = smoothstep(1.5, 0.4, r);
    finalColor *= vignette;

    gl_FragColor = vec4(finalColor, 1.0);
}
